excludedSubjectNames = {'HERO_instantiationCheck', 'boxAModulationCheck', 'temperatureCheck', 'MELA_0122', 'BoxA_ND09', 'BoxA_ND07', 'tortureTest_boxD_1', 'MELA_0137'};
for ii = 1:56
excludedSubjectNames{end+1} = ['tortureTest_', num2str(ii)];
end
for ii = 1:70
excludedSubjectNames{end+1} = ['tortureTest_day2_', num2str(ii)];
end
for ii = 2:17
    excludedSubjectNames{end+1} = ['tortureTest_boxD_', num2str(ii)];
end
OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'LightFluxDirection', ...
'visualizedProperty' , 'SMinusLMContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames ...
);

% subject notes:
% MELA_0126: no showed for session 3 on 6/25
% MELA_0127: for session 1 on 6/28, oneLight failed
% MELA_0121: for session 2 on 5/2, aborted because of tech failure
% MELA_0134: for session 1 on 5/3, actually a screening experiment 