excludedSubjectNames = {'HERO_instantiationCheck', 'boxAModulationCheck', 'temperatureCheck', 'BoxA_ND09', 'BoxA_ND07', 'tortureTest_boxD_1', 'MELA_0137'};
for ii = 1:56
excludedSubjectNames{end+1} = ['tortureTest_', num2str(ii)];
end
for ii = 1:70
excludedSubjectNames{end+1} = ['tortureTest_day2_', num2str(ii)];
end
for ii = 2:17
    excludedSubjectNames{end+1} = ['tortureTest_boxD_', num2str(ii)];
end

calibrations = {'2018-05-29', '2018-07-11'};
saveDir = fullfile(getpref('OLApproach_Squint', 'DataPath'), '../MELA_analysis/Experiments/OLApproach_Squint/SquintToPulse/admin');

%% LMS validations
OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'MaxLMSDirection', ...
'visualizedProperty' , 'SMinusLMContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [-0.3 0.3], 'limits', [-0.2 0.2], 'calibrations', calibrations, 'saveDir', saveDir ...
);

OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'MaxLMSDirection', ...
'visualizedProperty' , 'LMinusMContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [-0.3 0.3], 'limits', [-0.2 0.2], 'calibrations', calibrations, 'saveDir', saveDir ...
);

OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'MaxLMSDirection', ...
'visualizedProperty' , 'MelanopsinContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [-0.3 0.3], 'limits', [-0.2 0.2], 'calibrations', calibrations, 'saveDir', saveDir ...
);

OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'MaxLMSDirection', ...
'visualizedProperty' , 'LMSContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [3.75 4.25], 'limits', [3.75 4.25], 'calibrations', calibrations, 'saveDir', saveDir ...
);

%% Mel validations
OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'MaxMelDirection', ...
'visualizedProperty' , 'SMinusLMContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [-0.3 0.3], 'limits', [-0.2 0.2], 'calibrations', calibrations, 'saveDir', saveDir ...
);

OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'MaxMelDirection', ...
'visualizedProperty' , 'LMinusMContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [-0.3 0.3], 'limits', [-0.2 0.2], 'calibrations', calibrations, 'saveDir', saveDir ...
);

OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'MaxMelDirection', ...
'visualizedProperty' , 'LMSContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [-0.3 0.3], 'limits', [-0.2 0.2], 'calibrations', calibrations, 'saveDir', saveDir ...
);

OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'MaxMelDirection', ...
'visualizedProperty' , 'MelanopsinContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [3.75 4.25], 'limits', [3.75 4.25], 'calibrations', calibrations, 'saveDir', saveDir ...
);

%% LightFlux validations
OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'LightFluxDirection', ...
'visualizedProperty' , 'SMinusLMContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [-0.3 0.3], 'limits', [-0.2 0.2], 'calibrations', calibrations, 'saveDir', saveDir ...
);

OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'LightFluxDirection', ...
'visualizedProperty' , 'LMinusMContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [-0.3 0.3], 'limits', [-0.2 0.2], 'calibrations', calibrations, 'saveDir', saveDir ...
);

OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'LightFluxDirection', ...
'visualizedProperty' , 'LMSContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [3.75 4.25], 'limits', [3.75 4.25], 'calibrations', calibrations, 'saveDir', saveDir ...
);

OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'LightFluxDirection', ...
'visualizedProperty' , 'MelanopsinContrast', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [3.75 4.25], 'limits', [3.75 4.25], 'calibrations', calibrations, 'saveDir', saveDir ...
);
%% stimulus non-specific validaitons
OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'LightFluxDirection', ...
'visualizedProperty' , 'backgroundLuminance', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'yLim', [150 275], 'limits', [160.685 254.6685], 'calibrations', calibrations, 'saveDir', saveDir ...
);


OLPlotValidationTimeSeries(...
'approachName', 'OLApproach_Squint', ...
'protocolName', 'SquintToPulse', ...
'objectType',   'DirectionObjects', ...
'objectName',   'LightFluxDirection', ...
'visualizedProperty' , 'boxTemperature', ...
'visualizedStatistics', 'medians and data points', ...
'excludedSubjectNames', excludedSubjectNames, ...
'calibrations', calibrations, 'yLim', [26 30], 'saveDir', saveDir ...
);


% subject notes:
% MELA_0126: no showed for session 3 on 6/25
% MELA_0127: for session 1 on 6/28, oneLight failed
% MELA_0121: for session 2 on 5/2, aborted because of tech failure
% MELA_0134: for session 1 on 5/3, actually a screening experiment 
% MELA_0147: for session 3 on 7/25, no showed because was in the midst of a
% migraine